package com.zcbspay.platform.hz.batch.business.message.pojo;
// default package
// Generated 2017-3-22 14:50:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TChnPaymentDeta generated by hbm2java
 */
@Entity
@Table(name = "T_CHN_PAYMENT_DETA")
public class ChnPaymentDetaDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -8220331263541280971L;
	private long tid;
	private Long batchtid;
	private String batchno;
	private String chargingunit;
	private String transdate;
	private String txid;
	private String debtoraccountno;
	private String creditorbranchcode;
	private String creditorname;
	private String creditoraccountno;
	private String currencysymbol;
	private Long amount;
	private String paymenttooltype;
	private String postscript;
	private String additional;
	private String additionallen;
	private String msgauthcode;
	private String rspmsgid;
	private String rspstatus;
	private String rsprejectcode;
	private String rsprejectinformation;
	private String rspdate;
	private String nettingdate;
	private String txnseqno;
	private String notes;
	private String remarks;

	public ChnPaymentDetaDO() {
	}

	public ChnPaymentDetaDO(long tid) {
		this.tid = tid;
	}

	public ChnPaymentDetaDO(long tid, Long batchtid, String batchno,
			String chargingunit, String transdate, String txid,
			String debtoraccountno, String creditorbranchcode,
			String creditorname, String creditoraccountno,
			String currencysymbol, Long amount, String paymenttooltype,
			String postscript, String additional, String additionallen,
			String msgauthcode, String rspmsgid, String rspstatus,
			String rsprejectcode, String rsprejectinformation, String rspdate,
			String nettingdate, String txnseqno, String notes, String remarks) {
		this.tid = tid;
		this.batchtid = batchtid;
		this.batchno = batchno;
		this.chargingunit = chargingunit;
		this.transdate = transdate;
		this.txid = txid;
		this.debtoraccountno = debtoraccountno;
		this.creditorbranchcode = creditorbranchcode;
		this.creditorname = creditorname;
		this.creditoraccountno = creditoraccountno;
		this.currencysymbol = currencysymbol;
		this.amount = amount;
		this.paymenttooltype = paymenttooltype;
		this.postscript = postscript;
		this.additional = additional;
		this.additionallen = additionallen;
		this.msgauthcode = msgauthcode;
		this.rspmsgid = rspmsgid;
		this.rspstatus = rspstatus;
		this.rsprejectcode = rsprejectcode;
		this.rsprejectinformation = rsprejectinformation;
		this.rspdate = rspdate;
		this.nettingdate = nettingdate;
		this.txnseqno = txnseqno;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_chn_payment_deta") 
	@SequenceGenerator(name="seq_chn_payment_deta",sequenceName="SEQ_CHN_PAYMENT_DETA",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "BATCHTID", precision = 12, scale = 0)
	public Long getBatchtid() {
		return this.batchtid;
	}

	public void setBatchtid(Long batchtid) {
		this.batchtid = batchtid;
	}

	@Column(name = "BATCHNO", length = 32)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Column(name = "CHARGINGUNIT", length = 10)
	public String getChargingunit() {
		return this.chargingunit;
	}

	public void setChargingunit(String chargingunit) {
		this.chargingunit = chargingunit;
	}

	@Column(name = "TRANSDATE", length = 8)
	public String getTransdate() {
		return this.transdate;
	}

	public void setTransdate(String transdate) {
		this.transdate = transdate;
	}

	@Column(name = "TXID", length = 16)
	public String getTxid() {
		return this.txid;
	}

	public void setTxid(String txid) {
		this.txid = txid;
	}

	@Column(name = "DEBTORACCOUNTNO", length = 32)
	public String getDebtoraccountno() {
		return this.debtoraccountno;
	}

	public void setDebtoraccountno(String debtoraccountno) {
		this.debtoraccountno = debtoraccountno;
	}

	@Column(name = "CREDITORBRANCHCODE", length = 14)
	public String getCreditorbranchcode() {
		return this.creditorbranchcode;
	}

	public void setCreditorbranchcode(String creditorbranchcode) {
		this.creditorbranchcode = creditorbranchcode;
	}

	@Column(name = "CREDITORNAME", length = 120)
	public String getCreditorname() {
		return this.creditorname;
	}

	public void setCreditorname(String creditorname) {
		this.creditorname = creditorname;
	}

	@Column(name = "CREDITORACCOUNTNO", length = 32)
	public String getCreditoraccountno() {
		return this.creditoraccountno;
	}

	public void setCreditoraccountno(String creditoraccountno) {
		this.creditoraccountno = creditoraccountno;
	}

	@Column(name = "CURRENCYSYMBOL", length = 3)
	public String getCurrencysymbol() {
		return this.currencysymbol;
	}

	public void setCurrencysymbol(String currencysymbol) {
		this.currencysymbol = currencysymbol;
	}

	@Column(name = "AMOUNT", precision = 12, scale = 0)
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "PAYMENTTOOLTYPE", length = 1)
	public String getPaymenttooltype() {
		return this.paymenttooltype;
	}

	public void setPaymenttooltype(String paymenttooltype) {
		this.paymenttooltype = paymenttooltype;
	}

	@Column(name = "POSTSCRIPT", length = 16)
	public String getPostscript() {
		return this.postscript;
	}

	public void setPostscript(String postscript) {
		this.postscript = postscript;
	}

	@Column(name = "ADDITIONAL", length = 2)
	public String getAdditional() {
		return this.additional;
	}

	public void setAdditional(String additional) {
		this.additional = additional;
	}

	@Column(name = "ADDITIONALLEN", length = 3)
	public String getAdditionallen() {
		return this.additionallen;
	}

	public void setAdditionallen(String additionallen) {
		this.additionallen = additionallen;
	}

	@Column(name = "MSGAUTHCODE", length = 8)
	public String getMsgauthcode() {
		return this.msgauthcode;
	}

	public void setMsgauthcode(String msgauthcode) {
		this.msgauthcode = msgauthcode;
	}

	@Column(name = "RSPMSGID", length = 35)
	public String getRspmsgid() {
		return this.rspmsgid;
	}

	public void setRspmsgid(String rspmsgid) {
		this.rspmsgid = rspmsgid;
	}

	@Column(name = "RSPSTATUS", length = 4)
	public String getRspstatus() {
		return this.rspstatus;
	}

	public void setRspstatus(String rspstatus) {
		this.rspstatus = rspstatus;
	}

	@Column(name = "RSPREJECTCODE", length = 4)
	public String getRsprejectcode() {
		return this.rsprejectcode;
	}

	public void setRsprejectcode(String rsprejectcode) {
		this.rsprejectcode = rsprejectcode;
	}

	@Column(name = "RSPREJECTINFORMATION", length = 210)
	public String getRsprejectinformation() {
		return this.rsprejectinformation;
	}

	public void setRsprejectinformation(String rsprejectinformation) {
		this.rsprejectinformation = rsprejectinformation;
	}

	@Column(name = "RSPDATE", length = 14)
	public String getRspdate() {
		return this.rspdate;
	}

	public void setRspdate(String rspdate) {
		this.rspdate = rspdate;
	}

	@Column(name = "NETTINGDATE", length = 14)
	public String getNettingdate() {
		return this.nettingdate;
	}

	public void setNettingdate(String nettingdate) {
		this.nettingdate = nettingdate;
	}

	@Column(name = "TXNSEQNO", length = 16)
	public String getTxnseqno() {
		return this.txnseqno;
	}

	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
