package com.zcbspay.platform.hz.batch.business.message.pojo;
// default package
// Generated 2017-3-23 11:31:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TChnProtcolDownLog generated by hbm2java
 */
@Entity
@Table(name = "T_CHN_PROTCOL_DOWN_LOG")
public class ChnProtcolDownLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 5544368022635535570L;
	private long tid;
	private String msgtype;
	private String servicetype;
	private String transmitleg;
	private String receiver;
	private String transdate;
	private String transtime;
	private String operatorcode;
	private String chargingunit;
	private String signdate;
	private String downloadtype;
	private String rspcode;
	private String rspmsg;
	private String notes;
	private String remarks;

	public ChnProtcolDownLogDO() {
	}

	public ChnProtcolDownLogDO(long tid) {
		this.tid = tid;
	}

	public ChnProtcolDownLogDO(long tid, String msgtype, String servicetype,
			String transmitleg, String receiver, String transdate,
			String transtime, String operatorcode, String chargingunit,
			String signdate, String downloadtype, String rspcode,
			String rspmsg, String notes, String remarks) {
		this.tid = tid;
		this.msgtype = msgtype;
		this.servicetype = servicetype;
		this.transmitleg = transmitleg;
		this.receiver = receiver;
		this.transdate = transdate;
		this.transtime = transtime;
		this.operatorcode = operatorcode;
		this.chargingunit = chargingunit;
		this.signdate = signdate;
		this.downloadtype = downloadtype;
		this.rspcode = rspcode;
		this.rspmsg = rspmsg;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_chn_protcol_down_log") 
	@SequenceGenerator(name="seq_chn_protcol_down_log",sequenceName="SEQ_CHN_PROTCOL_DOWN_LOG",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGTYPE", length = 6)
	public String getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(String msgtype) {
		this.msgtype = msgtype;
	}

	@Column(name = "SERVICETYPE", length = 2)
	public String getServicetype() {
		return this.servicetype;
	}

	public void setServicetype(String servicetype) {
		this.servicetype = servicetype;
	}

	@Column(name = "TRANSMITLEG", length = 10)
	public String getTransmitleg() {
		return this.transmitleg;
	}

	public void setTransmitleg(String transmitleg) {
		this.transmitleg = transmitleg;
	}

	@Column(name = "RECEIVER", length = 10)
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "TRANSDATE", length = 8)
	public String getTransdate() {
		return this.transdate;
	}

	public void setTransdate(String transdate) {
		this.transdate = transdate;
	}

	@Column(name = "TRANSTIME", length = 6)
	public String getTranstime() {
		return this.transtime;
	}

	public void setTranstime(String transtime) {
		this.transtime = transtime;
	}

	@Column(name = "OPERATORCODE", length = 8)
	public String getOperatorcode() {
		return this.operatorcode;
	}

	public void setOperatorcode(String operatorcode) {
		this.operatorcode = operatorcode;
	}

	@Column(name = "CHARGINGUNIT", length = 10)
	public String getChargingunit() {
		return this.chargingunit;
	}

	public void setChargingunit(String chargingunit) {
		this.chargingunit = chargingunit;
	}

	@Column(name = "SIGNDATE", length = 8)
	public String getSigndate() {
		return this.signdate;
	}

	public void setSigndate(String signdate) {
		this.signdate = signdate;
	}

	@Column(name = "DOWNLOADTYPE", length = 1)
	public String getDownloadtype() {
		return this.downloadtype;
	}

	public void setDownloadtype(String downloadtype) {
		this.downloadtype = downloadtype;
	}

	@Column(name = "RSPCODE", length = 4)
	public String getRspcode() {
		return this.rspcode;
	}

	public void setRspcode(String rspcode) {
		this.rspcode = rspcode;
	}

	@Column(name = "RSPMSG", length = 256)
	public String getRspmsg() {
		return this.rspmsg;
	}

	public void setRspmsg(String rspmsg) {
		this.rspmsg = rspmsg;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
