package com.zcbspay.platform.hz.batch.business.message.pojo;
// default package
// Generated 2017-3-23 11:04:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TChnProtocolSignDeta generated by hbm2java
 */
@Entity
@Table(name = "T_CHN_PROTOCOL_SIGN_DETA")
public class ChnProtocolSignDetaDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 8614271246213042909L;
	private long tid;
	private Long batchtid;
	private String batchno;
	private String operatetype;
	private String chargingunit;
	private String authnumber;
	private String signdate;
	private String meterobjnumber;
	private String meterobjname;
	private String debtorname;
	private String debtoraccountno;
	private String debtorbranchcode;
	private String debtoraddress;
	private String notes;
	private String remarks;

	public ChnProtocolSignDetaDO() {
	}

	public ChnProtocolSignDetaDO(long tid) {
		this.tid = tid;
	}

	public ChnProtocolSignDetaDO(long tid, Long batchtid, String batchno,
			String operatetype, String chargingunit, String authnumber,
			String signdate, String meterobjnumber, String meterobjname,
			String debtorname, String debtoraccountno, String debtorbranchcode,
			String debtoraddress, String notes, String remarks) {
		this.tid = tid;
		this.batchtid = batchtid;
		this.batchno = batchno;
		this.operatetype = operatetype;
		this.chargingunit = chargingunit;
		this.authnumber = authnumber;
		this.signdate = signdate;
		this.meterobjnumber = meterobjnumber;
		this.meterobjname = meterobjname;
		this.debtorname = debtorname;
		this.debtoraccountno = debtoraccountno;
		this.debtorbranchcode = debtorbranchcode;
		this.debtoraddress = debtoraddress;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_chn_protocol_sign_deta") 
	@SequenceGenerator(name="seq_chn_protocol_sign_deta",sequenceName="SEQ_CHN_PROTOCOL_SIGN_DETA",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "BATCHTID", precision = 12, scale = 0)
	public Long getBatchtid() {
		return this.batchtid;
	}

	public void setBatchtid(Long batchtid) {
		this.batchtid = batchtid;
	}

	@Column(name = "BATCHNO", length = 32)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Column(name = "OPERATETYPE", length = 1)
	public String getOperatetype() {
		return this.operatetype;
	}

	public void setOperatetype(String operatetype) {
		this.operatetype = operatetype;
	}

	@Column(name = "CHARGINGUNIT", length = 10)
	public String getChargingunit() {
		return this.chargingunit;
	}

	public void setChargingunit(String chargingunit) {
		this.chargingunit = chargingunit;
	}

	@Column(name = "AUTHNUMBER", length = 12)
	public String getAuthnumber() {
		return this.authnumber;
	}

	public void setAuthnumber(String authnumber) {
		this.authnumber = authnumber;
	}

	@Column(name = "SIGNDATE", length = 8)
	public String getSigndate() {
		return this.signdate;
	}

	public void setSigndate(String signdate) {
		this.signdate = signdate;
	}

	@Column(name = "METEROBJNUMBER", length = 20)
	public String getMeterobjnumber() {
		return this.meterobjnumber;
	}

	public void setMeterobjnumber(String meterobjnumber) {
		this.meterobjnumber = meterobjnumber;
	}

	@Column(name = "METEROBJNAME", length = 120)
	public String getMeterobjname() {
		return this.meterobjname;
	}

	public void setMeterobjname(String meterobjname) {
		this.meterobjname = meterobjname;
	}

	@Column(name = "DEBTORNAME", length = 120)
	public String getDebtorname() {
		return this.debtorname;
	}

	public void setDebtorname(String debtorname) {
		this.debtorname = debtorname;
	}

	@Column(name = "DEBTORACCOUNTNO", length = 32)
	public String getDebtoraccountno() {
		return this.debtoraccountno;
	}

	public void setDebtoraccountno(String debtoraccountno) {
		this.debtoraccountno = debtoraccountno;
	}

	@Column(name = "DEBTORBRANCHCODE", length = 14)
	public String getDebtorbranchcode() {
		return this.debtorbranchcode;
	}

	public void setDebtorbranchcode(String debtorbranchcode) {
		this.debtorbranchcode = debtorbranchcode;
	}

	@Column(name = "DEBTORADDRESS", length = 120)
	public String getDebtoraddress() {
		return this.debtoraddress;
	}

	public void setDebtoraddress(String debtoraddress) {
		this.debtoraddress = debtoraddress;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
