package com.zcbspay.platform.hz.batch.business.message.pojo;
// default package
// Generated 2017-3-24 13:42:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TChnReconDownLog generated by hbm2java
 */
@Entity
@Table(name = "T_CHN_RECON_DOWN_LOG")
public class ChnReconDownLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -7760155338767762985L;
	private long tid;
	private String msgtype;
	private String servicetype;
	private String transmitleg;
	private String receiver;
	private String transdate;
	private String transtime;
	private String operatorcode;
	private String sendercode;
	private String downloaddate;
	private String downloadtype;
	private String localdate;
	private String localtime;
	private String notes;
	private String remarks;

	public ChnReconDownLogDO() {
	}

	public ChnReconDownLogDO(long tid) {
		this.tid = tid;
	}

	public ChnReconDownLogDO(long tid, String msgtype, String servicetype,
			String transmitleg, String receiver, String transdate,
			String transtime, String operatorcode, String sendercode,
			String downloaddate, String downloadtype, String localdate,
			String localtime, String notes, String remarks) {
		this.tid = tid;
		this.msgtype = msgtype;
		this.servicetype = servicetype;
		this.transmitleg = transmitleg;
		this.receiver = receiver;
		this.transdate = transdate;
		this.transtime = transtime;
		this.operatorcode = operatorcode;
		this.sendercode = sendercode;
		this.downloaddate = downloaddate;
		this.downloadtype = downloadtype;
		this.localdate = localdate;
		this.localtime = localtime;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_chn_recon_down_log") 
	@SequenceGenerator(name="seq_chn_recon_down_log",sequenceName="SEQ_CHN_RECON_DOWN_LOG",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGTYPE", length = 6)
	public String getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(String msgtype) {
		this.msgtype = msgtype;
	}

	@Column(name = "SERVICETYPE", length = 2)
	public String getServicetype() {
		return this.servicetype;
	}

	public void setServicetype(String servicetype) {
		this.servicetype = servicetype;
	}

	@Column(name = "TRANSMITLEG", length = 10)
	public String getTransmitleg() {
		return this.transmitleg;
	}

	public void setTransmitleg(String transmitleg) {
		this.transmitleg = transmitleg;
	}

	@Column(name = "RECEIVER", length = 10)
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "TRANSDATE", length = 8)
	public String getTransdate() {
		return this.transdate;
	}

	public void setTransdate(String transdate) {
		this.transdate = transdate;
	}

	@Column(name = "TRANSTIME", length = 6)
	public String getTranstime() {
		return this.transtime;
	}

	public void setTranstime(String transtime) {
		this.transtime = transtime;
	}

	@Column(name = "OPERATORCODE", length = 8)
	public String getOperatorcode() {
		return this.operatorcode;
	}

	public void setOperatorcode(String operatorcode) {
		this.operatorcode = operatorcode;
	}

	@Column(name = "SENDERCODE", length = 10)
	public String getSendercode() {
		return this.sendercode;
	}

	public void setSendercode(String sendercode) {
		this.sendercode = sendercode;
	}

	@Column(name = "DOWNLOADDATE", length = 8)
	public String getDownloaddate() {
		return this.downloaddate;
	}

	public void setDownloaddate(String downloaddate) {
		this.downloaddate = downloaddate;
	}

	@Column(name = "DOWNLOADTYPE", length = 2)
	public String getDownloadtype() {
		return this.downloadtype;
	}

	public void setDownloadtype(String downloadtype) {
		this.downloadtype = downloadtype;
	}

	@Column(name = "LOCALDATE", length = 8)
	public String getLocaldate() {
		return this.localdate;
	}

	public void setLocaldate(String localdate) {
		this.localdate = localdate;
	}

	@Column(name = "LOCALTIME", length = 6)
	public String getLocaltime() {
		return this.localtime;
	}

	public void setLocaltime(String localtime) {
		this.localtime = localtime;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
