package com.zcbspay.platform.hz.batch.business.message.pojo;
// default package
// Generated 2017-3-23 10:00:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TChnSignInOutLog generated by hbm2java
 */
@Entity
@Table(name = "T_CHN_SIGN_IN_OUT_LOG")
public class ChnSignInOutLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 894119589824214674L;
	private long tid;
	private String msgtype;
	private String servicetype;
	private String transmitleg;
	private String receiver;
	private String transdate;
	private String transtime;
	private String operatorcode;
	private String signpartycode;
	private String signdate;
	private String signtime;
	private String signtype;
	private String rspcode;
	private String notes;
	private String remarks;

	public ChnSignInOutLogDO() {
	}

	public ChnSignInOutLogDO(long tid) {
		this.tid = tid;
	}

	public ChnSignInOutLogDO(long tid, String msgtype, String servicetype,
			String transmitleg, String receiver, String transdate,
			String transtime, String operatorcode, String signpartycode,
			String signdate, String signtime, String signtype,
			String rspcode, String notes, String remarks) {
		this.tid = tid;
		this.msgtype = msgtype;
		this.servicetype = servicetype;
		this.transmitleg = transmitleg;
		this.receiver = receiver;
		this.transdate = transdate;
		this.transtime = transtime;
		this.operatorcode = operatorcode;
		this.signpartycode = signpartycode;
		this.signdate = signdate;
		this.signtime = signtime;
		this.signtype = signtype;
		this.rspcode = rspcode;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_chn_sign_in_out_log") 
	@SequenceGenerator(name="seq_chn_sign_in_out_log",sequenceName="SEQ_CHN_SIGN_IN_OUT_LOG",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGTYPE", length = 6)
	public String getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(String msgtype) {
		this.msgtype = msgtype;
	}

	@Column(name = "SERVICETYPE", length = 2)
	public String getServicetype() {
		return this.servicetype;
	}

	public void setServicetype(String servicetype) {
		this.servicetype = servicetype;
	}

	@Column(name = "TRANSMITLEG", length = 10)
	public String getTransmitleg() {
		return this.transmitleg;
	}

	public void setTransmitleg(String transmitleg) {
		this.transmitleg = transmitleg;
	}

	@Column(name = "RECEIVER", length = 10)
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "TRANSDATE", length = 8)
	public String getTransdate() {
		return this.transdate;
	}

	public void setTransdate(String transdate) {
		this.transdate = transdate;
	}

	@Column(name = "TRANSTIME", length = 6)
	public String getTranstime() {
		return this.transtime;
	}

	public void setTranstime(String transtime) {
		this.transtime = transtime;
	}

	@Column(name = "OPERATORCODE", length = 8)
	public String getOperatorcode() {
		return this.operatorcode;
	}

	public void setOperatorcode(String operatorcode) {
		this.operatorcode = operatorcode;
	}

	@Column(name = "SIGNPARTYCODE", length = 10)
	public String getSignpartycode() {
		return this.signpartycode;
	}

	public void setSignpartycode(String signpartycode) {
		this.signpartycode = signpartycode;
	}

	@Column(name = "SIGNDATE", length = 8)
	public String getSigndate() {
		return this.signdate;
	}

	public void setSigndate(String signdate) {
		this.signdate = signdate;
	}

	@Column(name = "SIGNTIME", length = 6)
	public String getSigntime() {
		return this.signtime;
	}

	public void setSigntime(String signtime) {
		this.signtime = signtime;
	}

	@Column(name = "SIGNTYPE", length = 1)
	public String getSigntype() {
		return this.signtype;
	}

	public void setSigntype(String signtype) {
		this.signtype = signtype;
	}

	@Column(name = "RSPCODE", length = 2)
	public String getRspcode() {
		return this.rspcode;
	}

	public void setRspcode(String rspcode) {
		this.rspcode = rspcode;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
