package com.zcbspay.platform.hz.batch.business.message.pojo;
// default package
// Generated 2017-3-24 14:07:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TChnTxn generated by hbm2java
 */
@Entity
@Table(name = "T_CHN_TXN")
public class ChnTxnDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 2380171811266452090L;
	private long tid;
	private String txnseqno;
	private String instiid;
	private String busicode;
	private String chargingunit;
	private String transdate;
	private String txid;
	private String creditorbranchcode;
	private String creditoraccountno;
	private String creditorname;
	private String debtorbranchcode;
	private String debtoraccountno;
	private String debtorname;
	private String currencysymbol;
	private Long amount;
	private String meterobjnumber;
	private String authnumber;
	private String vouchernumber;
	private String billnumber;
	private String systrcno;
	private String rspcode;
	private String settledate;
	private String settlestatus;
	private Long proid;
	private String status;
	private String result;
	private Long logid;
	private String notes;
	private String remarks;

	public ChnTxnDO() {
	}

	public ChnTxnDO(long tid) {
		this.tid = tid;
	}

	public ChnTxnDO(long tid, String txnseqno, String instiid, String busicode,
			String chargingunit, String transdate, String txid,
			String creditorbranchcode, String creditoraccountno,
			String creditorname, String debtorbranchcode,
			String debtoraccountno, String debtorname, String currencysymbol,
			Long amount, String meterobjnumber, String authnumber,
			String vouchernumber, String billnumber, String systrcno,
			String rspcode, String settledate, String settlestatus, Long proid,
			String status, String result, Long logid, String notes,
			String remarks) {
		this.tid = tid;
		this.txnseqno = txnseqno;
		this.instiid = instiid;
		this.busicode = busicode;
		this.chargingunit = chargingunit;
		this.transdate = transdate;
		this.txid = txid;
		this.creditorbranchcode = creditorbranchcode;
		this.creditoraccountno = creditoraccountno;
		this.creditorname = creditorname;
		this.debtorbranchcode = debtorbranchcode;
		this.debtoraccountno = debtoraccountno;
		this.debtorname = debtorname;
		this.currencysymbol = currencysymbol;
		this.amount = amount;
		this.meterobjnumber = meterobjnumber;
		this.authnumber = authnumber;
		this.vouchernumber = vouchernumber;
		this.billnumber = billnumber;
		this.systrcno = systrcno;
		this.rspcode = rspcode;
		this.settledate = settledate;
		this.settlestatus = settlestatus;
		this.proid = proid;
		this.status = status;
		this.result = result;
		this.logid = logid;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_chn_txn") 
	@SequenceGenerator(name="seq_chn_txn",sequenceName="SEQ_CHN_TXN",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "TXNSEQNO", length = 16)
	public String getTxnseqno() {
		return this.txnseqno;
	}

	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	@Column(name = "INSTIID", length = 11)
	public String getInstiid() {
		return this.instiid;
	}

	public void setInstiid(String instiid) {
		this.instiid = instiid;
	}

	@Column(name = "BUSICODE", length = 8)
	public String getBusicode() {
		return this.busicode;
	}

	public void setBusicode(String busicode) {
		this.busicode = busicode;
	}

	@Column(name = "CHARGINGUNIT", length = 10)
	public String getChargingunit() {
		return this.chargingunit;
	}

	public void setChargingunit(String chargingunit) {
		this.chargingunit = chargingunit;
	}

	@Column(name = "TRANSDATE", length = 8)
	public String getTransdate() {
		return this.transdate;
	}

	public void setTransdate(String transdate) {
		this.transdate = transdate;
	}

	@Column(name = "TXID", length = 16)
	public String getTxid() {
		return this.txid;
	}

	public void setTxid(String txid) {
		this.txid = txid;
	}

	@Column(name = "CREDITORBRANCHCODE", length = 14)
	public String getCreditorbranchcode() {
		return this.creditorbranchcode;
	}

	public void setCreditorbranchcode(String creditorbranchcode) {
		this.creditorbranchcode = creditorbranchcode;
	}

	@Column(name = "CREDITORACCOUNTNO", length = 32)
	public String getCreditoraccountno() {
		return this.creditoraccountno;
	}

	public void setCreditoraccountno(String creditoraccountno) {
		this.creditoraccountno = creditoraccountno;
	}

	@Column(name = "CREDITORNAME", length = 120)
	public String getCreditorname() {
		return this.creditorname;
	}

	public void setCreditorname(String creditorname) {
		this.creditorname = creditorname;
	}

	@Column(name = "DEBTORBRANCHCODE", length = 14)
	public String getDebtorbranchcode() {
		return this.debtorbranchcode;
	}

	public void setDebtorbranchcode(String debtorbranchcode) {
		this.debtorbranchcode = debtorbranchcode;
	}

	@Column(name = "DEBTORACCOUNTNO", length = 32)
	public String getDebtoraccountno() {
		return this.debtoraccountno;
	}

	public void setDebtoraccountno(String debtoraccountno) {
		this.debtoraccountno = debtoraccountno;
	}

	@Column(name = "DEBTORNAME", length = 120)
	public String getDebtorname() {
		return this.debtorname;
	}

	public void setDebtorname(String debtorname) {
		this.debtorname = debtorname;
	}

	@Column(name = "CURRENCYSYMBOL", length = 3)
	public String getCurrencysymbol() {
		return this.currencysymbol;
	}

	public void setCurrencysymbol(String currencysymbol) {
		this.currencysymbol = currencysymbol;
	}

	@Column(name = "AMOUNT", precision = 12, scale = 0)
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "METEROBJNUMBER", length = 20)
	public String getMeterobjnumber() {
		return this.meterobjnumber;
	}

	public void setMeterobjnumber(String meterobjnumber) {
		this.meterobjnumber = meterobjnumber;
	}

	@Column(name = "AUTHNUMBER", length = 12)
	public String getAuthnumber() {
		return this.authnumber;
	}

	public void setAuthnumber(String authnumber) {
		this.authnumber = authnumber;
	}

	@Column(name = "VOUCHERNUMBER", length = 16)
	public String getVouchernumber() {
		return this.vouchernumber;
	}

	public void setVouchernumber(String vouchernumber) {
		this.vouchernumber = vouchernumber;
	}

	@Column(name = "BILLNUMBER", length = 32)
	public String getBillnumber() {
		return this.billnumber;
	}

	public void setBillnumber(String billnumber) {
		this.billnumber = billnumber;
	}

	@Column(name = "SYSTRCNO", length = 32)
	public String getSystrcno() {
		return this.systrcno;
	}

	public void setSystrcno(String systrcno) {
		this.systrcno = systrcno;
	}

	@Column(name = "RSPCODE", length = 6)
	public String getRspcode() {
		return this.rspcode;
	}

	public void setRspcode(String rspcode) {
		this.rspcode = rspcode;
	}

	@Column(name = "SETTLEDATE", length = 8)
	public String getSettledate() {
		return this.settledate;
	}

	public void setSettledate(String settledate) {
		this.settledate = settledate;
	}

	@Column(name = "SETTLESTATUS", length = 1)
	public String getSettlestatus() {
		return this.settlestatus;
	}

	public void setSettlestatus(String settlestatus) {
		this.settlestatus = settlestatus;
	}

	@Column(name = "PROID", precision = 10, scale = 0)
	public Long getProid() {
		return this.proid;
	}

	public void setProid(Long proid) {
		this.proid = proid;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "RESULT", length = 2)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "LOGID", precision = 12, scale = 0)
	public Long getLogid() {
		return this.logid;
	}

	public void setLogid(Long logid) {
		this.logid = logid;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
