package com.zcbspay.platform.hz.batch.pojo;
// default package
// Generated 2017-3-21 14:01:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TChnAgreement generated by hbm2java
 */
@Entity
@Table(name = "T_CHN_AGREEMENT")
public class ChnAgreementDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -847829983332483397L;
	private long tid;
	private String transdate;
	private String transtime;
	private String chargingunit;
	private String entrustdate;
	private String entrustnum;
	private String meterobjnumber;
	private String debtorbranchcode;
	private String debtorname;
	private String debtoraccountno;
	private String rspdate;
	private String rspcode;
	private String operatorcode;
	private String notes;
	private String remarks;
	private String status;
	public ChnAgreementDO() {
	}

	public ChnAgreementDO(long tid) {
		this.tid = tid;
	}

	public ChnAgreementDO(long tid, String transdate, String transtime,
			String chargingunit, String entrustdate, String entrustnum,
			String meterobjnumber, String debtorbranchcode, String debtorname,
			String debtoraccountno, String rspdate, String rspcode,
			String operatorcode, String notes, String remarks) {
		this.tid = tid;
		this.transdate = transdate;
		this.transtime = transtime;
		this.chargingunit = chargingunit;
		this.entrustdate = entrustdate;
		this.entrustnum = entrustnum;
		this.meterobjnumber = meterobjnumber;
		this.debtorbranchcode = debtorbranchcode;
		this.debtorname = debtorname;
		this.debtoraccountno = debtoraccountno;
		this.rspdate = rspdate;
		this.rspcode = rspcode;
		this.operatorcode = operatorcode;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_chn_agreement") 
	@SequenceGenerator(name="seq_chn_agreement",sequenceName="SEQ_CHN_AGREEMENT",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "TRANSDATE", length = 8)
	public String getTransdate() {
		return this.transdate;
	}

	public void setTransdate(String transdate) {
		this.transdate = transdate;
	}

	@Column(name = "TRANSTIME", length = 6)
	public String getTranstime() {
		return this.transtime;
	}

	public void setTranstime(String transtime) {
		this.transtime = transtime;
	}

	@Column(name = "CHARGINGUNIT", length = 10)
	public String getChargingunit() {
		return this.chargingunit;
	}

	public void setChargingunit(String chargingunit) {
		this.chargingunit = chargingunit;
	}

	@Column(name = "ENTRUSTDATE", length = 8)
	public String getEntrustdate() {
		return this.entrustdate;
	}

	public void setEntrustdate(String entrustdate) {
		this.entrustdate = entrustdate;
	}

	@Column(name = "ENTRUSTNUM", length = 60)
	public String getEntrustnum() {
		return this.entrustnum;
	}

	public void setEntrustnum(String entrustnum) {
		this.entrustnum = entrustnum;
	}

	@Column(name = "METEROBJNUMBER", length = 20)
	public String getMeterobjnumber() {
		return this.meterobjnumber;
	}

	public void setMeterobjnumber(String meterobjnumber) {
		this.meterobjnumber = meterobjnumber;
	}

	@Column(name = "DEBTORBRANCHCODE", length = 14)
	public String getDebtorbranchcode() {
		return this.debtorbranchcode;
	}

	public void setDebtorbranchcode(String debtorbranchcode) {
		this.debtorbranchcode = debtorbranchcode;
	}

	@Column(name = "DEBTORNAME", length = 120)
	public String getDebtorname() {
		return this.debtorname;
	}

	public void setDebtorname(String debtorname) {
		this.debtorname = debtorname;
	}

	@Column(name = "DEBTORACCOUNTNO", length = 32)
	public String getDebtoraccountno() {
		return this.debtoraccountno;
	}

	public void setDebtoraccountno(String debtoraccountno) {
		this.debtoraccountno = debtoraccountno;
	}

	@Column(name = "RSPDATE", length = 14)
	public String getRspdate() {
		return this.rspdate;
	}

	public void setRspdate(String rspdate) {
		this.rspdate = rspdate;
	}

	@Column(name = "RSPCODE", length = 6)
	public String getRspcode() {
		return this.rspcode;
	}

	public void setRspcode(String rspcode) {
		this.rspcode = rspcode;
	}

	@Column(name = "OPERATORCODE", length = 8)
	public String getOperatorcode() {
		return this.operatorcode;
	}

	public void setOperatorcode(String operatorcode) {
		this.operatorcode = operatorcode;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	
	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}
