package com.zcbspay.platform.hz.batch.pojo;
// default package
// Generated 2017-5-9 14:44:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * THzAgencyInfo generated by hbm2java
 */
@Entity
@Table(name = "T_HZ_AGENCY_INFO")
public class HzAgencyInfoDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -2760955359960036576L;
	private long tid;
	private String merchno;
	private String busicode;
	private String chargingunit;
	private String busisort;
	private String status;
	private Long inuser;
	private Date intime;
	private String notes;
	private String remarks;

	public HzAgencyInfoDO() {
	}

	public HzAgencyInfoDO(long tid) {
		this.tid = tid;
	}

	public HzAgencyInfoDO(long tid, String merchno, String busicode,
			String chargingunit, String busisort, String status, Long inuser,
			Date intime, String notes, String remarks) {
		this.tid = tid;
		this.merchno = merchno;
		this.busicode = busicode;
		this.chargingunit = chargingunit;
		this.busisort = busisort;
		this.status = status;
		this.inuser = inuser;
		this.intime = intime;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MERCHNO", length = 15)
	public String getMerchno() {
		return this.merchno;
	}

	public void setMerchno(String merchno) {
		this.merchno = merchno;
	}

	@Column(name = "BUSICODE", length = 8)
	public String getBusicode() {
		return this.busicode;
	}

	public void setBusicode(String busicode) {
		this.busicode = busicode;
	}

	@Column(name = "CHARGINGUNIT", length = 10)
	public String getChargingunit() {
		return this.chargingunit;
	}

	public void setChargingunit(String chargingunit) {
		this.chargingunit = chargingunit;
	}

	@Column(name = "BUSISORT", length = 8)
	public String getBusisort() {
		return this.busisort;
	}

	public void setBusisort(String busisort) {
		this.busisort = busisort;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "INUSER", precision = 12, scale = 0)
	public Long getInuser() {
		return this.inuser;
	}

	public void setInuser(Long inuser) {
		this.inuser = inuser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INTIME", length = 7)
	public Date getIntime() {
		return this.intime;
	}

	public void setIntime(Date intime) {
		this.intime = intime;
	}

	@Column(name = "NOTES", length = 512)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 512)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
